Repository GoogleCloudPlatform/ai-on-gke, pull requests merged in 2025-05, with the labels that each got.

#1104 Deprecate E2E GenAI application
  tutorials-and-examples/genAI-LLM/e2e-genai-langchain-app/README.md
Labels: kind/cleanup

#1107 Orchestration deprecation
  tutorials-and-examples/workflow-orchestration/indexed-job/Dockerfile
  tutorials-and-examples/workflow-orchestration/indexed-job/README.md
  tutorials-and-examples/workflow-orchestration/indexed-job/mnist.py
  tutorials-and-examples/workflow-orchestration/jobset/pytorch/README.md
Labels: kind/cleanup

#1097 Migrate ray-on-gke to the new repository
  .github/workflows/ci.yaml
  applications/ray/README.md
  applications/ray/backend.tf
  applications/ray/main.tf
  applications/ray/metadata.display.yaml
  applications/ray/metadata.yaml
  applications/ray/outputs.tf
  applications/ray/tfvars_examples/README.md
  applications/ray/tfvars_examples/raycluster-with-gcsfuse-volumes.tfvars
  applications/ray/tfvars_examples/raycluster-with-grafana-dashboard.tfvars
  applications/ray/tfvars_examples/raycluster-with-iap-auth.tfvars
  applications/ray/tfvars_examples/raycluster-with-workload-identity.tfvars
  applications/ray/tfvars_examples/simple-raycluster-with-existing-gke-cluster.tfvars
  applications/ray/tfvars_examples/simple-raycluster-with-new-gke-cluster.tfvars
  applications/ray/variables.tf
  applications/ray/versions.tf
  applications/ray/workloads.tfvars
  ray-on-gke/README.md
  ray-on-gke/templates
Labels: kind/other

#1109 refactor: updated links to reflect new ai-on-gke repo
  tutorials-and-examples/nvidia-bionemo/README.md
  tutorials-and-examples/nvidia-bionemo/base/kustomization.yaml
  tutorials-and-examples/nvidia-bionemo/base/monitoring/rbac.yaml
  tutorials-and-examples/nvidia-bionemo/base/monitoring/tensorboard-deployment.yaml
  tutorials-and-examples/nvidia-bionemo/base/monitoring/tensorboard-service.yaml
  tutorials-and-examples/nvidia-bionemo/base/namespace.yaml
  tutorials-and-examples/nvidia-bionemo/base/storage/kustomization.yaml
  tutorials-and-examples/nvidia-bionemo/base/storage/pvcs.yaml
  tutorials-and-examples/nvidia-bionemo/base/storage/storage-class.yaml
  tutorials-and-examples/nvidia-bionemo/fine-tuning/README.md
  tutorials-and-examples/nvidia-bionemo/fine-tuning/inference/Dockerfile
  tutorials-and-examples/nvidia-bionemo/fine-tuning/inference/deployment.yaml
  tutorials-and-examples/nvidia-bionemo/fine-tuning/inference/inference_server.py
  tutorials-and-examples/nvidia-bionemo/fine-tuning/inference/kustomization.yaml
  tutorials-and-examples/nvidia-bionemo/fine-tuning/job/finetuning.py
  tutorials-and-examples/nvidia-bionemo/fine-tuning/job/job.yaml
  tutorials-and-examples/nvidia-bionemo/fine-tuning/job/kustomization.yaml
  tutorials-and-examples/nvidia-bionemo/pretraining/.DS_Store
  tutorials-and-examples/nvidia-bionemo/pretraining/LICENSE
  tutorials-and-examples/nvidia-bionemo/pretraining/README.md
  tutorials-and-examples/nvidia-bionemo/pretraining/configmaps/startup-script.yaml
  tutorials-and-examples/nvidia-bionemo/pretraining/configmaps/training-config.yaml
  tutorials-and-examples/nvidia-bionemo/pretraining/images/tensorboard-results.png
  tutorials-and-examples/nvidia-bionemo/pretraining/job.yaml
  tutorials-and-examples/nvidia-bionemo/pretraining/kustomization.yaml
  tutorials-and-examples/nvidia-bionemo/requirements.txt
  tutorials-and-examples/nvidia-nim/README.md
  tutorials-and-examples/nvidia-nim/blueprints/README.md
  tutorials-and-examples/nvidia-nim/blueprints/digitalhuman/README.md
  tutorials-and-examples/nvidia-nim/blueprints/digitalhuman/digital-human-nimbp.yaml
  tutorials-and-examples/nvidia-nim/blueprints/digitalhuman/https.md
  tutorials-and-examples/nvidia-nim/blueprints/digitalhuman/speech_to_text_sample.wav
  tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/README.md
  tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/nim-bp-generative-virtual-screening.yaml
  tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/nim-storage-filestore.yaml
  tutorials-and-examples/nvidia-nim/blueprints/drugdiscovery/test-generative-virtual-screening.py
Labels: kind/cleanup

#1110 Slurm on GKE migration to new repo
  modules/slurm-cluster/main.tf
  modules/slurm-cluster/manifest-templates/00-configmap-slurm-config.yml
  modules/slurm-cluster/manifest-templates/00-configmap-slurmdb-config.yml
  modules/slurm-cluster/manifest-templates/00-secret-database-auth.yml
  modules/slurm-cluster/manifest-templates/00-secret-munge-key.yml
  modules/slurm-cluster/manifest-templates/01-pvc-slurm-shared-storage.yml
  modules/slurm-cluster/manifest-templates/01-pvc-var-lib-mysql.yml
  modules/slurm-cluster/manifest-templates/01-pvc-var-spool-slurmctld.yml
  modules/slurm-cluster/manifest-templates/02-svc-deployment-login.yml
  modules/slurm-cluster/manifest-templates/02-svc-deployment-mysql.yml
  modules/slurm-cluster/manifest-templates/02-svc-deployment-slurmdbd.yml
  modules/slurm-cluster/manifest-templates/03-svc-statefulset-slurmctld.yml
  modules/slurm-cluster/manifest-templates/04-svc-mysql.yml
  modules/slurm-cluster/manifest-templates/04-svc-slurmctld-0.yml
  modules/slurm-cluster/manifest-templates/04-svc-slurmdb.yml
  modules/slurm-cluster/outputs.tf
  modules/slurm-cluster/variables.tf
  modules/slurm-nodeset/main.tf
  modules/slurm-nodeset/manifest-templates/03-svc-statefulset-slurmd.yml
  modules/slurm-nodeset/manifest-templates/04-svc-slurmd.yml
  modules/slurm-nodeset/variables.tf
  slurm-on-gke/.gitignore
  slurm-on-gke/README.md
  slurm-on-gke/image/Dockerfile
  slurm-on-gke/image/docker-entrypoint.sh
  slurm-on-gke/infrastructure/main.tf
  slurm-on-gke/infrastructure/providers.tf
  slurm-on-gke/infrastructure/slurm.tf
  slurm-on-gke/infrastructure/variables.tf
  slurm-on-gke/main.tf
  slurm-on-gke/providers.tf
  slurm-on-gke/solution-architecture.png
  slurm-on-gke/variables.tf
Labels: kind/cleanup

#1114 Remove kuberay-tpu-webhook files and duplicate TPU guide
  ray-on-gke/guides/tpu/README.md
  ray-on-gke/tpu/kuberay-tpu-webhook/Dockerfile
  ray-on-gke/tpu/kuberay-tpu-webhook/Makefile
  ray-on-gke/tpu/kuberay-tpu-webhook/README.md
  ray-on-gke/tpu/kuberay-tpu-webhook/Troubleshooting.md
  ray-on-gke/tpu/kuberay-tpu-webhook/certs/cert.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/cloudbuild.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/deployments/deployment.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/deployments/mutating-webhook-cfg.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/deployments/validating-webhook-cfg.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/deployments/webhook-svc.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/go.mod
  ray-on-gke/tpu/kuberay-tpu-webhook/go.sum
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/.helmignore
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/Chart.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/templates/cert.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/templates/deployment.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/templates/mutating-webhook-cfg.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/templates/validating-webhook-cfg.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/templates/webhook-svc.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/helm-chart/values.yaml
  ray-on-gke/tpu/kuberay-tpu-webhook/main.go
  ray-on-gke/tpu/kuberay-tpu-webhook/samples/tpu-test.py
  ray-on-gke/tpu/kuberay-tpu-webhook/webhook_main_test.go
Labels: kind/cleanup

#1115 migrate repo
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/.gitignore
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/README.md
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/create-clusters.sh
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/create-multikueue-kubeconfig.sh
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/deploy-multikueue.sh
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/dws-multi-worker.yaml
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/dws-multi.yaml
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/job-multi-dws-autopilot.yaml
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/prom.yaml
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/tf/clusters.tf
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/tf/outputs.tf
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/tf/variables.tf
  tutorials-and-examples/workflow-orchestration/dws-multiclusters-example/tf/versions.tf
Labels: kind/other

#1118 Deprecations
  benchmarks/65k-cpu-nodes-simulated-ai-benchmark.md
  benchmarks/README.md
  benchmarks/accelerator-based-ai-benchmark.md
  benchmarks/benchmark/README.md
  benchmarks/benchmark/dataset/README.md
  benchmarks/benchmark/dataset/ShareGPT_v3_unflitered_cleaned_split/README.md
  benchmarks/benchmark/tools/README.md
  benchmarks/benchmark/tools/dlio/README.md
  benchmarks/benchmark/tools/locust-load-inference/README.md
  benchmarks/benchmark/tools/model-load-benchmark/README.md
  benchmarks/benchmark/tools/profile-generator/README.md
  benchmarks/inference-server/README.md
  benchmarks/inference-server/jetstream/README.md
  benchmarks/inference-server/text-generation-inference/README.md
  benchmarks/inference-server/triton/README.md
  benchmarks/inference-server/vllm/README.md
  benchmarks/infra/accelerator-cluster/README.md
  benchmarks/infra/accelerator-cluster/stage-1/README.md
  benchmarks/infra/accelerator-cluster/stage-2/README.md
  benchmarks/orchestration/README.md
Labels: kind/cleanup

#1120 Deprecate tools w/ no owners
  tools/dcgm-on-gke/README.md
  tools/dcgm-on-gke/grafana/gke-dcgm-grafana-dashboard.json
  tools/dcgm-on-gke/grafana/grafana.yml
  tools/dcgm-on-gke/grafana/proxy/Dockerfile
  tools/dcgm-on-gke/grafana/proxy/README.md
  tools/dcgm-on-gke/grafana/proxy/attempt-register-vm-on-proxy.sh
  tools/dcgm-on-gke/grafana/proxy/get_proxy_url.py
  tools/dcgm-on-gke/grafana/proxy/get_proxy_url_test.py
  tools/dcgm-on-gke/grafana/proxy/requirements.txt
  tools/dcgm-on-gke/quickstart/dcgm_quickstart.yml
  tools/dcgm-on-gke/quickstart/gke-dcgm-dashboard.yml
  tools/saxml-on-gke/README.md
  tools/saxml-on-gke/httpserver/Dockerfile
  tools/saxml-on-gke/httpserver/README.md
  tools/saxml-on-gke/httpserver/http_server.py
  tools/saxml-on-gke/httpserver/requirements-build.txt
  tools/saxml-on-gke/httpserver/requirements.txt
  tools/saxml-on-gke/single-host-inference/gptj/README.md
  tools/saxml-on-gke/single-host-inference/gptj/admin-server.yaml
  tools/saxml-on-gke/single-host-inference/gptj/http-server.yaml
  tools/saxml-on-gke/single-host-inference/gptj/load-balancer.yaml
  tools/saxml-on-gke/single-host-inference/gptj/model-server.yaml
Labels: kind/documentation, kind/cleanup
